### ISSUE TITLE
attention model

### ISSUE THREAD

**Issue by HaminyG** [0aqz0/SLR#1]
Excellent job!! Cause I am a fresh bird in this area, could you please tell me what is l and g which are as inputs for linearattentionblock?

**Comment by 0aqz0** [comment]
I add the attention blocks and refer to this paper: Learn to Pay Attention(ICLR2018). And this figure shows the architecture in the paper.

![image](https://user-images.githubusercontent.com/32999259/77373030-13a60b80-6da2-11ea-9a29-1f30ee83459d.png)

To my understanding, l represents features extracted from different layers and g represents features extracted from the final layer.

You can check out this paper. In my job, I try to add similar attention blocks to 3D ResNet. But the result now is a bit worse than 3D ResNet without attention :) and I am still tuning the model.

**Comment by HaminyG** [comment]
Thanks so much. This figure makes more sense.&nbsp;



发自我的iPhone


------------------ Original ------------------

**Comment by 0aqz0** [comment]
You're welcome.
