### ISSUE TITLE
isolated数据集下载链接失效

### ISSUE THREAD

**Issue by hufengshuo07** [0aqz0/SLR#11]
CSL的有些数据集的百度云链接挂了，您这边还有其他下载路径吗

**Comment by 0aqz0** [comment]
链接: https://pan.baidu.com/s/1EJIbiFh0SGPUhteuux53Ug 提取码: 3qsu 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by hufengshuo07** [comment]
谢谢谢谢！
