### ISSUE TITLE
孤立词手语数据集

### ISSUE THREAD

**Issue by kznpt** [0aqz0/SLR#13]
请问，您有500类别的骨架信息的文件吗?我在分享的百度网盘里下载的数据集，没有找到骨架信息的txt文件。

**Comment by 0aqz0** [comment]
链接: https://pan.baidu.com/s/1rch4V_3f9cSXd5yr-lJuHw 提取码: vn8k 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by kznpt** [comment]
您好，请问提取码是多少？

**Comment by kznpt** [comment]
非常感谢
