### ISSUE TITLE
Cnnlstm

### ISSUE THREAD

**Issue by HaminyG** [0aqz0/SLR#2]
Hi,
It's me again. I tried to use your cnnlstm model which is Rescnnlstm, but the loss isn't going down. So I am wondering where I was wrong. I set the same parameter that you provided. How many epochs did you train for 92% accuracy? Thanks

**Comment by 0aqz0** [comment]
Did you use the cropped data provided in the link?

**Comment by HaminyG** [comment]
I am not actually. But I got it work. Thanks



发自我的iPhone


------------------ Original ------------------

**Comment by 0aqz0** [comment]
👍 You’re welcome.
