### ISSUE TITLE
连续句子测试问题

### ISSUE THREAD

**Issue by EriAquarius** [0aqz0/SLR#28]
你好，我想测试我训练好的连续句子的模型，但是test.py文件好像是针对的是孤立词模型，请问我该怎样测试连续句子的模型呢，谢谢

**Comment by 0aqz0** [comment]
你好，validation.py里有val_seq2seq。

https://github.com/0aqz0/SLR/blob/a1fc68b0ab4f3198efe767bc99745b9d31a13b0c/validation.py#L37



-----原始邮件-----
发件人:shring56 ***@***.***>
发送时间:2022-12-07 10:27:07 (星期三)
收件人: 0aqz0/SLR ***@***.***>
抄送: Subscribed ***@***.***>
主题: [0aqz0/SLR] 连续句子测试问题 (Issue #28)






你好，我想测试我训练好的连续句子的模型，但是test.py文件好像是针对的是孤立词模型，请问我该怎样测试连续句子的模型呢，谢谢

**Comment by EriAquarius** [comment]
非常感谢
