### ISSUE TITLE
Issue on corpus.txt

### ISSUE THREAD

**Issue by dudwo1128** [0aqz0/SLR#8]
Hello

I am currently working on a continuous seq2seq code.
I am trying to work on our dataset.
However, I cannot check dictionary.txt and corpus.txt file.
Can you upload files here or explain the composition of each file?

Thank you.

**Comment by 0aqz0** [comment]
corpus.txt is composed of sentences used for training.
[corpus.txt](https://github.com/0aqz0/SLR/files/5603449/corpus.txt)

dictionary.txt is composed of words used in these sentences.
[dictionary.txt](https://github.com/0aqz0/SLR/files/5603447/dictionary.txt)

**Comment by dudwo1128** [comment]
Hello, this Young-Jae, Park from Korea.

Thank you for your consideration.
Best regards

2020년 11월 26일 (목) 오후 11:09, Haodong Zhang <notifications@github.com>님이 작성:

**Comment by 0aqz0** [comment]
You are welcome.:smile:
